### ISSUE TITLE
One Tree Planted

### ISSUE THREAD

**Issue by Cotabe** [Giveth/project-nominations#14]
Already in the platform through the Giving Block integration and have raised 150+ USD in Giveth.

They have a relationship with Maker DAO too now.

They seem to be very open to crypto.

Would be interesting to explore with them, but also with Maker DAO. Then they could get GIVbacks.

**Comment by melodysongq** [comment]
@Cotabe  if they are with the Giving Block, it's more likely they will remain that way for the following reasons:  

1) the Giving Block gives them a widget to put on their website so that giving can be channeled through there;  
2) they don't have to manage wallet, which is preferred by most accounting/finance division of the nonprofit: 
3) their money is off-ramped and given to them in FIAT so they don't have to worry about that part either.     

We could approach to 
1) inform them that they are also on Giveth, are they interested to also provide some updates on Giveth since Giveth gives donors rewards;  If not, what's the reason as we are collecting some answers for those who don't want to engage with Giveth if that's the case
2) if MakerDAO is interested to give through Giveth platform and receive GIVbacks then they can steward specific donors like MakerDAO on the Giveth platform.  We will need to talk to MakerDAO as a donor instead.

**Comment by SnakeGH** [comment]
Added them to our CRM and made initial outreach.

**Comment by SnakeGH** [comment]
Spoke with their Director (Cassandra) and they would like to hold off for the moment, timing isnt right for them, before exploring other fundraising platforms
